applications/departamento/urls.py
from django.urls import path
from . import views


app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(), name = 'departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name = 'nuevo_departamento'),
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'empleado_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<departamento>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name = 'empleado_add'),
    path('success/', views.SuccessView.as_view(), name = 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name = 'modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name = 'eliminarempleado'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name = 'empleados_admin'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/departamento/models.py
from email.policy import default
from enum import unique
from operator import mod
from pyexpat import model
from tabnanny import verbose
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length = 50)
    shor_name = models.CharField('Nombre corto', max_length = 20)
    anulate = models.BooleanField('Anulado', default = False)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['name']
        unique.together = ('name','shor_name')

    def __str__(self) -> str:
        return str(self.id) + '-' + self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.empleado.models import Empleado
from .models import Departamento

# Create your views here.
class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('Estamos en el form_valid')
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

#Vista para listar departamentos
class DepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    model = Departamento
    context_object_name = 'departamentos'

templates/departamento/lista.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Lista departamentos    
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista de departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td><a class="button warning" href="{% url 'empleado_app:empleados_area' departamento.shor_name %}">Ver empleados</a></td>
                        </tr>
                        {% endfor %}
                            
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Registrar nuevo departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registro de nuevo departamento con su respectivo empleado</h1>
            <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombres: 
                        {{form.nombre}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos
                        {{form.apellidos}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>                    
                </div>
                <div class="medium-6 cell">
                    <label>Area: 
                        {{form.shorname}}
                    </label>
                </div>
            </form>
            <button class="button success" type="submit">Guardar</button>
        </div>

    </div>


{% endblock content %}
    
    
   