applications/empleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'empleado_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<departamento>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name = 'empleado_add'),
    path('success/', views.SuccessView.as_view(), name = 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name = 'modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name = 'eliminarempleado'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name = 'empleados_admin'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/empleado/models.py
from distutils.command.upload import upload
from operator import mod
from random import choices
from tabnanny import verbose
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length = 50)

    class Meta: 
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad

JOB_CHOICES = (
    ('0', 'Contador'),
    ('1', 'Administrador'),
    ('2', 'Economista'),
    ('3', 'Otro'),
)

class Empleado(models.Model):
    first_name = models.CharField('Nombres', max_length = 60)
    last_name = models.CharField('Apellidos', max_length = 60)
    full_name = models.CharField('Nombres completos', max_length =120, blank=True)
    job = models.CharField('Trabajo', max_length = 50, choices = JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete = models.CASCADE)
    avatar = models.ImageField(upload_to = 'empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_de_vida = RichTextField()

    class Meta:
        verbose_name = 'Mis subditos'
        verbose_name_plural = 'Clase obrera'
        ordering = ['first_name']


    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/empleado/forms.py
from socket import fromshare
from django import forms 
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )

        widgets = {
            'habilidades' : forms.CheckboxSelectMultiple()
        }

applications/empleado/views.py
from struct import pack
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from applications import empleado
from .models import Empleado

from .forms import EmpleadoForm

# Create your views here.

class ListAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    model = Empleado
    context_object_name = 'lista'
    paginate_by = 2
    ordering = 'first_name'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            full_name__icontains = palabra_clave
        )

        print(f'Lista de resultados: {lista}')
        return lista



class ListaEmpleadosAdmin(ListView):
    template_name = 'empleado/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado



class ListByAreaEmpleado(ListView):
    template_name = 'empleado/list_by_area.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        area = self.kwargs['departamento']
        lista = Empleado.objects.filter(
        departamento__shor_name = area
        )
        return lista

class ListEmpleadoByKword(ListView):
    template_name = 'empleado/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )

        print(f'Lista de resultados: {lista}')
        return lista

class ListHabilidadesEmpleado(ListView):
    template_name = 'empleado/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
       empleado = Empleado.objects.get(id=2)
       return empleado.habilidades.all()

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'empleado/detail_empleado.html'


class SuccessView(TemplateView):
    template_name = 'empleado/success.html'


class EmpleadoCreateView(CreateView):
    template_name = 'empleado/add.html'
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def form_valid(self,form):
        empleado = form.save()
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = 'empleado/update.html'
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['first_name'])
        return super().post(request,*args,**kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'empleado/delete.html'
    success_url = reverse_lazy('empleado_app:empleados_admin')




#DESARROLLO DEL APLICATIVO COMO PRIMER PROYECTO

class InicioView(TemplateView):
    template_name = 'inicio.html'

templates/empleado/add.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Registrar empleado
{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1>Registro de empleados</h1>
            <form enctype="multipart/form-data" class="cell grid-x grid-margin-x" method="POST"> {% csrf_token %}
                
                <div class="medium-6 cell">
                    <label>Nombres:
                      {{form.first_name}}
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Apellidos:
                      {{form.last_name}}
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Trabajo: 
                      {{form.job}}
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Departamento: 
                      {{form.departamento}}
                    </label>
                </div>

                <div class="medium-12 cell">
                    <label>Habilidades: 
                      {{form.habilidades}}
                    </label>
                </div>

                <div class="medium-12 cell">
                    <label>Imagen: 
                      {{form.avatar}}
                    </label>
                </div>

                <div class="medium-12 cell">
                    <button type="submit" class="button success">Guardar</button>
                </div>

            </form>
        </div>

    </div>
    
{% endblock content %}
    

templates/empleado/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista empleados</title>
</head>
<body>
    <h1>Buscar empleados por palabra clave</h1>
    <form method = 'GET'> {% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="Ingrese el nombre aqui">
        <button type="submit">Buscar</button>
    </form>
    <h3>Lista de resultados</h3>
    <ul>        
        {% for h in habilidades %}
            <li>{{h}}</li>            
        {% endfor %}            
    </ul>
</body>
</html>

templates/empleado/delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar empleado: {{object.first_name}}</h1>

            <form class="cell" method="POST">{% csrf_token %}

                <div class="callout secondary">
                    <h5>¿Desea eliminar este empleado?</h5>
                    <button type="button" class="alert button">Eliminar</button>
                </div>              
            </form>
        </div>
    </div>
    
{% endblock content %}

templates/empleado/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.first_name }}
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class=" cell large-4 card" style="width: 300px;">
                <div class="card-divider">
                  {{empleado.get_job_display}}
                </div>
                
                {% if empleado.avatar %}
                    <img src="{{empleado.avatar.url}}">
                {% else %}
                    <img src="{% static 'img/sinfoto.jpg' %}">
                {% endif %}
                    
                
                <div class="card-section">
                  <h4>{{empleado.first_name}}</h4>
                  <h4>{{empleado.last_name}}</h4>
                  <h4>{{empleado.departamento.shor_name}}</h4>
                  <p><span class="label">Habilidades: </span></p>
                  <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all %}
                        <li>{{ h.habilidad }}</li>                        
                    {% endfor %}
                        
                  </ul>                 
                </div>
              </div>
        </div>
    </div>
{% endblock content %}

templates/empleado/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habilidades de empleados</title>
</head>
<body>
    <h1>Lista de habilidades por empleado</h1>
    <ul>
        
        {% for h in habilidades %}
            <li>{{ h }}</li>
        {% endfor %}
            
    </ul>
</body>
</html>

templates/empleado/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1>Lista de empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in object_list %}  
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver empleado</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>

    </div>

    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
              
              {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                </li>
              {% endif %}
                
              
              {% for pagina in paginator.page_range  %}

              <li class="curren"><span class="show-for-sr">You're on page></span><a href="?page={{pagina}}">{{pagina}}</a></li>                  
              
              {% endfor %}
                
                           
              {% if page_obj.has_next %}        
              <li class="pagination-next">
                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
              </li>
              {% endif %}

            </ul>
        </nav>
        {% endif %}
    </div>
    
</div>
{% endblock content %}

templates/empleado/list_by_area.html
{% extends 'base.html' %}

{% load static %}


{% block title %}  
    Lista de empleados por departamento
{% endblock title %}   

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area</div>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCIÓN</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for e in object_list %}  
                      <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver empleado</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>                    
    </div>
{% endblock content %}

templates/empleado/lista_empleados.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1>Lista de empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in object_list %}  
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td>
                        <a class="button success" href="{% url 'empleado_app:modificar_empleado' e.id %}">Editar</a>
                    </td>
                    <td>
                        <a class="button alert" href="{% url 'empleado_app:eliminarempleado' e.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>

    </div>

    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
              
              {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                </li>
              {% endif %}
                
              
              {% for pagina in paginator.page_range  %}

              <li class="curren"><span class="show-for-sr">You're on page></span><a href="?page={{pagina}}">{{pagina}}</a></li>                  
              
              {% endfor %}
                
                           
              {% if page_obj.has_next %}        
              <li class="pagination-next">
                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
              </li>
              {% endif %}

            </ul>
        </nav>
        {% endif %}
    </div>
    
</div>
{% endblock content %}

templates/empleado/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro Exitoso</title>
</head>
<body>
    <h1>Registro de la informacion ha sido exitoso</h1>
</body>
</html>

templates/empleado/update.html
{% extends 'base.html' %}


{% block title %}
    Editar empleado
{% endblock title %}
        
{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Actualizar empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                    <div class="medium-6 cell">
                        <label>
                            Nombres: {{form.first_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>
                            Apellidos: {{form.last_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>
                            Trabajo: {{form.job}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>
                            Departamento: {{form.departamento}}
                        </label>
                    </div>
                    <div class="cell">
                        <label>
                            Habilidades: {{form.habilidades}}
                        </label>
                    </div>
                    <div class="cell">
                        <button class="submit success button">Actualizar</button>
                    </div>
                </form>
            </div>            
        </div>        
    </div>
    
{% endblock content %}